[tool.poetry]
name = "django_adminlte3"
version = "0.0.1"
description = "django_adminlte3"
authors = ["voronadenis <d.vorona@forteholding.ru>"]
repository = "https://github.com/voronadenis/django_adminlte3"